# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

r:
- oldrel
- release
- devel

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

cache: packages

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  cleanup: false
  skip_cleanup: true

after_success:
  - Rscript -e 'covr::codecov()'
