# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: bionic

apt_packages:
  - libxml2-dev
  - libudunits2-dev

jobs:
  include:
  - r: release
  - r: devel
  - r: oldrel

cache: packages

# after_success:
#   - Rscript -e 'covr::codecov()'
